engines:
  eslint:
    enabled: true
    config:
      config: test/linters/.eslintrc
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - api/**/*
  - assets/js/**/*
  - "**.js"
exclude_paths:
- tests/**/*
- "assets/js/shared/*"
