engines:
  eslint:
    enabled: false
    config:
      config: tests/linters/.eslintrc
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - 09e2899562aa713dce4899fff9ecb2ff
    config:
      languages:
      - javascript
ratings:
  paths:
  - api/**/*
  - assets/js/**/*
  - "**.js"
exclude_paths:
- tests/**/*
- "assets/js/shared/*"
